# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on: push

jobs:
  test:
    env:
      RAILS_ENV: test

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # とりあえずBigSurでRubyがインストールできるようになるまでは2.6の最新verを利用
        # ruby-version: ['2.6', '2.7', '3.0']
        ruby-version: ['2.6.6']

    services:
      postgres:
        image: postgres:13.2
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: task_app_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Run Rubocop
      run: bundle exec rubocop

    - name: DB migration
      run: bundle exec rake db:migrate

    - name: yarn install
      run: yarn install

    - name: create screenshot dir
      run: mkdir tmp/screenshots && touch tmp/screenshots/.keep

    - name: Run RSpec
      run: bundle exec rspec spec

    - name: save screenshots
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: screenshots
        path: tmp/screenshots
